repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.6
    hooks:
      - id: ruff
        stages: [pre-commit]
        args: [--config=pyproject.toml, --fix]
      - id: ruff-format
        stages: [pre-commit]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        stages: [pre-commit]
        args: [--strict, --ignore-missing-imports, --config-file=pyproject.toml]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-merge-conflict
      - id: pretty-format-json
        args: ["--autofix", "--indent", "4"]
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: detect-private-key
