[project]
name = "map_genie"
version = "0.1.0"
description="Style Maps Easily in GQIS"
dependencies = [
    
]
authors = [
    {name = "Matthew McKee"},
]

[tool.isort]
profile = "black"

[tool.ruff]
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
]
include = ["*.py", "*.pyi"]

line-length = 88
indent-width = 4

target-version = "py38"

[tool.ruff.lint]
select = ["E", "W", "I", "N", "UP", "RUF", "PERF", "ERA", "PTH"]
ignore = ["D203", "D213", "RUF005", "N999"]

fixable = ["ALL"]
unfixable = []

dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

per-file-ignores = {"*/__init__.py" = ["F401", "F403" ,"E402"], "**/*.pyi" = ["D418"], "tests/*.py" = ["D"], "**/*.py" = ["D100"], "app/alembic/*.py" = ["D100", "I001"]}

[tool.ruff.format]
quote-style = "double"

indent-style = "space"

skip-magic-trailing-comma = false

line-ending = "auto"

[tool.mypy]
ignore_missing_imports = true
disable_error_code = ["call-arg", "no-untyped-def", "unused-ignore"]
disallow_untyped_defs = false
disallow_untyped_decorators = false
exclude = [
    "^app/alembic/.*",
]

[tool.pytest.ini_options]
addopts = "--ignore=db-data"