name: Release Plugin

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Set env
              run: echo "RELEASE_VERSION=$(git describe --tags)" >> $GITHUB_ENV

            - uses: actions/checkout@v2

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Install Python requirements
              run: uv venv && uv pip install qgis-plugin-ci

            - name: Package and deploy the zip
              run: >-
                  uv run qgis-plugin-ci release ${{ env.RELEASE_VERSION }}
                  --github-token ${{ secrets.GITHUB_TOKEN }}
                  --osgeo-username ${{ secrets.OSGEO_USERNAME }}
                  --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
                  --create-plugin-repo
