name: Release Plugin

on:
    push:
        tags:
            - "*"

jobs:
    release:
        runs-on: ubuntu-latest

        steps:
            - name: Set env
              run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

            - uses: actions/checkout@v2

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Install Python requirements
              run: uv venv && uv pip install qgis-plugin-ci six

            - name: Get current changelog
              run: uv run qgis-plugin-ci changelog ${{ env.TAG }} >> release.md

            - name: Setup Plugin Package
              run: mv LICENCE prettier_maps/

            - name: Create release on GitHub
              uses: ncipollo/release-action@v1.10.0
              with:
                  bodyFile: release.md
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Package and deploy the zip
              run: >-
                  uv run qgis-plugin-ci release ${{ env.TAG }}
                  --github-token ${{ secrets.GITHUB_TOKEN }}
                  --osgeo-username ${{ secrets.OSGEO_USERNAME }}
                  --osgeo-password ${{ secrets.OSGEO_PASSWORD }}
                  --create-plugin-repo
                  --allow-uncommitted-changes
