name: Deploy Documentation

on:
    workflow_dispatch:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.12"

            - name: Install MkDocs
              run: |
                  pip install -r requirements-docs.txt

            - name: Build and deploy docs
              run: |
                  mkdocs gh-deploy --force
