stages:
  - lint

before_script:
  - make venv

ruff:
  stage: lint
  image: python:3.12
  script:
    - make ruff
  only:
    changes:
      - tests/**/*
      - prettier_maps/**/*
mypy:
  stage: lint
  image: python:3.12
  script:
    - make mypy
  only:
    changes:
      - tests/**/*
      - prettier_maps/**/*

isort:
  stage: lint
  image: python:3.12
  script:
    - make isort
  only:
    changes:
      - tests/**/*
      - prettier_maps/**/*
